In [25]:
import numpy as np

In [26]:
arr1 = np.array([1,2,3,4,5])

In [27]:
arr1/

SyntaxError: invalid syntax (1138184093.py, line 1)

In [28]:
print(arr1)

[1 2 3 4 5]


In [29]:
type(arr1)

numpy.ndarray

In [30]:
# 0 dimension array 

a0 = np.array(10)

In [31]:
print(a0)

10


In [32]:
# used to determine the dimensions 


a0.ndim

0

In [33]:
#collection of n dimensional array is n+1 dimensional array 

In [34]:
#if we add elements in array of different dtypes the it converts all those elements in string 
  

In [35]:
arr2 = np.array([0,1,"saipvan", "matmari",True ])

In [36]:
type(arr2)

numpy.ndarray

In [37]:
arr2   # u11 is string

array(['0', '1', 'saipvan', 'matmari', 'True'], dtype='<U11')

In [38]:
arr3 = np.array([False,10])  # converts to integer 

In [39]:
arr3

array([ 0, 10])

In [44]:
# 2 dimension



a2= np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [45]:
a2

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [43]:
a2[1,1]

5

In [51]:
a2.ndim

3

In [59]:
a4 = np.array([[[[1,2,3]],[[12,13,14]]],[[[4,5,6]]],[[[7,8,9]]]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [53]:
a4

array([[[[1, 2, 3]]],


       [[[4, 5, 6]]],


       [[[7, 8, 9]]]])

In [57]:
a4[0]

IndexError: index 1 is out of bounds for axis 1 with size 1

In [66]:
arr5 =  np.array([1,5,3,43,51,67,47,28,8])

In [67]:
np.sort(arr5)

array([ 1,  3,  5,  8, 28, 43, 47, 51, 67])

In [68]:
print(arr5)

[ 1  5  3 43 51 67 47 28  8]


#np.insert("name",index,value)

In [70]:
arr5 = np.insert(arr5,1,15)

arr5

In [73]:
np.delete(arr5,1)

array([ 1,  5,  3, 43, 51, 67, 47, 28,  8])

np array doesnt have appent operation